#!/usr/bin/env bash
# Provision a fresh Ubuntu box (with an NVIDIA GPU + sudo) to run a full Orion scan.
# Installs: JDK 21 (Temurin), Joern, uv + a project venv (with the transformers pin the jina
# embedding model needs), the Claude Code CLI, and brings up Neo4j via the repo's docker-compose.
# Idempotent-ish: re-running skips work that's already done.
#
#   cd <this repo>            # lutherleo/orion @ remote-bench
#   bash bench/setup.sh
#
# After it finishes, authenticate the Claude CLI (see bench/README.md) and run:
#   bash bench/scan.sh /path/to/target/repo
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

JDK_VER="21.0.5+11"        # Temurin build; any 17+ works. Pinned for reproducibility.
JOERN_VER="v4.0.590"       # matches what this rig was validated against
say() { printf '\n\033[1m== %s ==\033[0m\n' "$*"; }

# ---------------------------------------------------------------- OS packages
say "apt packages"
sudo apt-get update -y
sudo apt-get install -y curl unzip tar xz-utils git ca-certificates python3 python3-venv jq

# ---------------------------------------------------------------- Docker (for Neo4j)
if ! command -v docker >/dev/null 2>&1; then
  say "Docker (for Neo4j)"
  curl -fsSL https://get.docker.com | sudo sh
  sudo usermod -aG docker "$USER" || true
  echo "NOTE: you may need to log out/in for docker group membership, or run docker with sudo."
fi

# ---------------------------------------------------------------- JDK 21 (Temurin), user-local
if [ ! -x "$HOME/jdk/current/bin/java" ]; then
  say "JDK $JDK_VER"
  mkdir -p "$HOME/jdk" && cd "$HOME/jdk"
  arch="$(uname -m)"; [ "$arch" = "aarch64" ] && jarch="aarch64" || jarch="x64"
  curl -fsSL -o jdk.tar.gz \
    "https://api.adoptium.net/v3/binary/latest/21/ga/linux/${jarch}/jdk/hotspot/normal/eclipse"
  tar xzf jdk.tar.gz && rm jdk.tar.gz
  ln -sfn "$HOME/jdk/$(ls -d jdk-*/ | head -1 | tr -d /)" "$HOME/jdk/current"
  cd "$REPO_ROOT"
fi
export JAVA_HOME="$HOME/jdk/current"
export PATH="$JAVA_HOME/bin:$PATH"
java -version

# ---------------------------------------------------------------- Joern
if [ ! -x "$HOME/joern/joern-cli/joern-parse" ]; then
  say "Joern $JOERN_VER"
  mkdir -p "$HOME/joern" && cd "$HOME/joern"
  arch="$(uname -m)"; [ "$arch" = "aarch64" ] && jz="linux-arm64" || jz="linux-x86_64"
  curl -fsSL -o joern-cli.zip \
    "https://github.com/joernio/joern/releases/download/${JOERN_VER}/joern-cli-${jz}.zip"
  unzip -q -o joern-cli.zip && rm joern-cli.zip
  cd "$REPO_ROOT"
fi
export JOERN_HOME="$HOME/joern/joern-cli"
"$JOERN_HOME/joern-parse" --version >/dev/null 2>&1 || true

# ---------------------------------------------------------------- uv + venv + Orion install
if ! command -v uv >/dev/null 2>&1; then
  say "uv"
  curl -LsSf https://astral.sh/uv/install.sh | sh
fi
export PATH="$HOME/.local/bin:$PATH"

say "Python venv + Orion (with semantic extras)"
uv venv .venv --python 3.12
# torch from the semantic extra ships CUDA support on Linux x86_64 by default (uses the GPU).
VIRTUAL_ENV="$REPO_ROOT/.venv" uv pip install -e ".[semantic,dev]"
# The jina embedding model breaks on transformers 5.x; pin below it (bench/orion_scan.py aliases
# the renamed config class so Orion's shim still imports).
VIRTUAL_ENV="$REPO_ROOT/.venv" uv pip install "transformers<5"
./.venv/bin/python - <<'PY'
import torch
print("torch", torch.__version__, "| CUDA available:", torch.cuda.is_available(),
      "|", (torch.cuda.get_device_name(0) if torch.cuda.is_available() else "CPU only"))
PY

# ---------------------------------------------------------------- Claude Code CLI
if ! command -v claude >/dev/null 2>&1 && [ ! -x "$HOME/.local/bin/claude" ]; then
  say "Claude Code CLI"
  curl -fsSL https://claude.ai/install.sh | bash
fi
"$HOME/.local/bin/claude" --version 2>/dev/null || claude --version

# ---------------------------------------------------------------- Neo4j (docker-compose)
say "Neo4j (docker compose up -d)"
DC="docker compose"; docker compose version >/dev/null 2>&1 || DC="docker-compose"
sudo $DC up -d 2>/dev/null || $DC up -d
echo -n "waiting for Neo4j on 7688 "
for _ in $(seq 1 60); do
  (exec 3<>/dev/tcp/127.0.0.1/7688) 2>/dev/null && { exec 3>&- 3<&-; echo "up"; break; }
  echo -n "."; sleep 2
done

# ---------------------------------------------------------------- env file for the run scripts
cat > "$REPO_ROOT/bench/env.sh" <<EOF
# sourced by bench/scan.sh — generated by setup.sh
export JAVA_HOME="$HOME/jdk/current"
export JOERN_HOME="$HOME/joern/joern-cli"
export PATH="\$HOME/.local/bin:\$JAVA_HOME/bin:\$PATH"
export NEO4J_URI="bolt://localhost:7688"
export NEO4J_USER="neo4j"
export NEO4J_PASSWORD="orion_dev_changeme"
export TOKENIZERS_PARALLELISM="false"
EOF

say "setup complete"
cat <<EOF
Next:
  1. Authenticate the Claude CLI on this box (one-time):
       claude          # interactive login, OR
       export ANTHROPIC_API_KEY=sk-ant-...   # in your shell / bench/env.sh
  2. Run a full scan:
       bash bench/scan.sh /path/to/target/repo
     Watch it live in another shell:
       ./.venv/bin/python bench/scan_watch.py
EOF
